services:
    yrt-db:
        hostname: yrt-db
        container_name: yrt-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_NAME}"
            PGPORT: "${DB_PORT}"
        networks:
            - yrt

    yrt-meilisearch:
        hostname: yrt-meilisearch
        container_name: yrt-meilisearch
        image: getmeili/meilisearch:latest
        restart: always
        networks:
            - yrt
        environment:
            MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"
            MEILI_ENV: "${MEILI_ENV:-development}"
            MEILI_HTTP_ADDR: "0.0.0.0:${MEILI_PORT}"
        volumes:
            - ./meili_data:/meili_data

    yrt-meilibridge:
        hostname: yrt-meilibridge
        depends_on:
        yrt-db:
            condition: service_healthy
        condition: service_healthy
        container_name: yrt-meilibridge
        image: binarytouch/meilibridge:latest
        restart: always
        networks:
            - yrt
        environment:
            POSTGRES_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@yrt-db:${DB_PORT}/${DB_NAME}"
            MEILISEARCH_URL: "http://yrt-meilisearch:${MEILI_PORT}"
            MEILISEARCH_API_KEY: "${MEILI_MASTER_KEY}"
        volumes:
            - "${MEILIBRIDGE_CONFIG}:/etc/meilibridge/config.yaml:ro"

    yrt:
        depends_on:
            - yrt-db
        image: goodm2ice/yorutracker
        restart: always
        networks:
            - yrt
            - traefik
        env_file: .env
        environment:
            DB_HOST: yrt-db
            ARCHIVEPATH: '/backup.xz'
        volumes:
            - "${ARCHIVEPATH}:/backup.xz"
            - ./images:/tracker-images
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik

            - traefik.http.routers.yrt.rule=Host(`${SUB_DOMAIN}.${DOMAINNAME_1}`)
            - traefik.http.routers.yrt.entrypoints=https
            - traefik.http.routers.yrt.tls=true
            - traefik.http.routers.yrt.tls.certresolver=letsencrypt
            - traefik.http.routers.yrt.service=yrt

            - traefik.http.routers.yrt-local.rule=Host(`${SUB_DOMAIN}.${DOMAINNAME_2}`)
            - traefik.http.routers.yrt-local.entrypoints=https
            - traefik.http.routers.yrt-local.tls=true
            - traefik.http.routers.yrt-local.tls.certresolver=local-ca
            - traefik.http.routers.yrt-local.service=yrt
            
            - traefik.http.services.yrt.loadbalancer.server.port=${FASTAPI_PORT}

            - homepage.group=Общедоступные
            - homepage.name=YoRuTracker
            - homepage.icon=si-utorrent
            - homepage.instance.public.href=https://${SUB_DOMAIN}.${DOMAINNAME_1}
            - homepage.instance.private.href=https://${SUB_DOMAIN}.${DOMAINNAME_2}
            - homepage.description=Локальный сервис поиска торрент-трекеров

networks:
    yrt:
        internal: true
    traefik:
        external: true
